---
- name: Provision WordPress server and restore oki2a24.com from BackWPup
  hosts: wp_server
  remote_user: ansible
  become: true
  roles:
    - role: common
      tags: common
    - role: mariadb
      tags: mariadb
    - role: nginx
      tags: nginx
    - role: php
      tags: php
    - role: php-fpm
      tags: php-fpm
    - role: wordpress
      tags: wordpress
    - role: ssl
      tags: ssl
