---
- name: Create WordPress directory
  file:
    path: "{{ wp_path }}"
    state: directory
    mode: 0755

#- name: Donwload BackWPup archived file
#  get_url:
#    url: "{{ bacwpup_zip_url }}"
#    dest: /tmp/backwpup.zip

- name: Install unzip
  yum:
    name: unzip
    state: latest

- name: Extract BackWPup
  unarchive:
    src: "{{ bacwpup_zip_file }}"
    #src: /tmp/backwpup.zip
    #src: "{{ bacwpup_zip_url }}"
    dest: "{{ wp_path }}"
    #remote_src: yes

#- name: Create WordPress DataBase
#  shell: /usr/local/bin/wp db create --path={{ wp_path }}

- name: Import WordPress DataBase
  shell: /usr/local/bin/wp db import {{ wp_db_file }} --path={{ wp_path }}

#- name: Download wp core
#  shell: /usr/local/bin/wp core download --locale=ja --path={{ wp_path }}
#  ignore_errors: yes
#
#- name: Generate wp config
#  shell: /usr/local/bin/wp core config --dbname={{ wp_db_name }} --dbuser={{ wp_db_user }} --dbpass={{ wp_db_password }}  --locale=ja --path={{ wp_path }}
#  ignore_errors: yes
#
#- name: Install wp
#  shell: /usr/local/bin/wp core install --url={{ wp_url }} --title={{ wp_title }} --admin_user={{ wp_admin_user }} --admin_password={{ wp_admin_password }} --admin_email={{ wp_admin_email }} --path={{ wp_path }}
#  ignore_errors: yes

- name: Change ownership of WordPress directory
  file:
    path: "{{ wp_path }}"
    owner: nginx
    group: nginx
    state: directory
    recurse: yes
