---
# http://nginx.org/en/linux_packages.html
- name: Copy nginx.repo
  copy:
    src: nginx.repo
    dest: /etc/yum/repos.d/

- name: Install nginx
  yum:
    name: nginx
    enablerepo: nginx
    state: latest

- name: Start and enable nginx service
  service:
    name: nginx.service
    state: started
    enabled: yes

- name: Insert firewalld rule for nginx
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes
