---
#- name: Add group "wordpress"
#  group: name=wordpress

  #- name: Add user "wordpress"
  #  user: name=wordpress group=wordpress home=/srv/wordpress/

- name: Create WordPress directory
  file:
    path: /srv/wordpress/
    state: directory
    mode: 0755

- name: Download wp core
  shell: /usr/local/bin/wp core download --locale=ja --path=/srv/wordpress/
  #become: yes
  #become_user: wordpress
  ignore_errors: yes

- name: Generate wp config
  shell: /usr/local/bin/wp core config --dbname={{ wp_db_name }} --dbuser={{ wp_db_user }} --dbpass={{ wp_db_password }}  --locale=ja --path=/srv/wordpress/
  #become: yes
  #become_user: wordpress
  ignore_errors: yes

- name: Install wp
  shell: /usr/local/bin/wp core install --url={{ wp_url }} --title={{ wp_title }} --admin_user={{ wp_admin_user }} --admin_password={{ wp_admin_password }} --admin_email={{ wp_admin_email }} --path=/srv/wordpress/
  #  become: yes
  #  become_user: wordpress
  ignore_errors: yes

- name: Change ownership of WordPress directory
  file:
    path: /srv/wordpress/
    #owner: wordpress
    #group: wordpress
    owner: nginx
    group: nginx
    state: directory
    recurse: yes
