---
- name: Install remi-release-7
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: Install php-fpm
  yum:
    name:
      - php
      - php-fpm
    enablerepo: remi-php72
    state: latest

- name: Start and enable php-fpm service
  service:
    name: php-fpm
    state: started
    enabled: yes
